name: Require Semantic Version Tag

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate SemVer in PR description
        run: |
          BODY="${{ github.event.pull_request.body }}"

          if [[ ! "$BODY" =~ Release-\v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "PR must contain: Release-vX.Y.Z (valid semantic version)"
            exit 1
          fi